### ISSUE TITLE
Add logo mode

### ISSUE THREAD

**Issue by hadess** [sdroege/gst-player#99]
When playing back audio, or video-less streams, gst-player should either clear the video sink so the background is all black when switching videos, or display a placeholder.

**Comment by sdroege** [comment]
I think this should be something to be handled by the UI toolkit integration IMHO. As on the GstPlayer/GStreamer side the best would could do is to show a single-frame video stream... and the widgets are currently blackening the background anyway if nothing is shown and could just do something different there.

I'll still keep this open so that we can consider that when making the Qt/QML and GTK+ UI toolkit integration public API.

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=765316
